Feature wikibase upgrade
MaRDI4NFDI/docker-wikibase pull request #31
Opened 2022-05-09 16:50 UTC by Hyper-Node

# MaRDI Pull Request

**Changes**:
- Version Update to 1_37 
- Latest MediaWiki docker container is 1_37 so it makes sense to stick with extensions to this. (And set the extensions in development to master if necessary) 
-  

**Instructions for PR review**:
- [x[ Conceptual Review (Logic etc...) 
- [x] Code Review (Review your implementation) 
- [ ] Checkout (Test changes locally) 

**Checklist for this PR**: 
- [ ] [Reviewers and Assignee specified.](https://docs.github.com/en/issues/tracking-your-work-with-issues/assigning-issues-and-pull-requests-to-other-github-users)
- [ ] [All related issues are linked.](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

2022-05-10 09:29 UTC, dajuno requested changes
I tested this locally (using ${DOLLAR}IP as mentioned in my comment), and get the following error from the mediawiki @localhost:

Fatal error: Uncaught Exception: Unable to open file /extensions/Wikibase/extension-repo.json: filemtime(): stat failed for /extensions/Wikibase/extension-repo.json in /var/www/html/includes/registration/ExtensionRegistry.php:182 Stack trace: #0 /var/www/html/includes/GlobalFunctions.php(52): ExtensionRegistry->queue('/extensions/Wik...') #1 /var/www/html/LocalSettings.php(52): wfLoadExtension('WikibaseReposit...', '/extensions/Wik...') #2 /var/www/html/includes/Setup.php(145): require_once('/var/www/html/L...') #3 /var/www/html/includes/WebStart.php(90): require_once('/var/www/html/i...') #4 /var/www/html/index.php(44): require('/var/www/html/i...') #5 {main} thrown in /var/www/html/includes/registration/ExtensionRegistry.php on line 182

also there are errors for the visualeditor extension

2022-05-10 09:35 UTC, Hyper-Node commented on LocalSettings.php.template
> +require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
Does running these maintenance on  your local installation of wikibase solve it ?: 
php maintenance/update.php 
php extensions/Wikibase/lib/maintenance/populateSitesTable.php

2022-05-10 09:48 UTC, Hyper-Node commented on LocalSettings.php.template
> +require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
However, uploaded dollar variant, this seems also to work locally for my setup.

2022-05-10 09:53 UTC, dajuno commented on LocalSettings.php.template
> +require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
In a second attempt, the previous error did not show (I'm pretty sure I did docker-compose down && docker volume prune, though). But now I am getting a deprecation warning:
![image](https://user-images.githubusercontent.com/12959445/167601716-cb258d59-43a9-4045-9b25-cb1e8724d50d.png)

2022-05-10 09:59 UTC, dajuno commented on LocalSettings.php.template
> +require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
I am not getting the `Unable to open file /extensions/Wikibase/extension-repo.json` error anymore. I guess the statistical evidence is good enough to ignore it ;)

2022-05-10 10:03 UTC, Hyper-Node commented on LocalSettings.php.template
> +require_once "$IP/extensions/Wikibase/client/ExampleSettings.php";
Yes, deprecation warning is also appearing here, but the skin still seems to show correctly, therefore this can be ignored atm.

2022-05-11 12:04 UTC, Hyper-Node commented
local setup of this is working fine with restored backup from mardi01. Beginning deployment.

2022-05-11 12:04 UTC, merged